# Generated by Django 5.0.2 on 2025-09-16 05:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom")),
                ("prenom", models.CharField(max_length=100, verbose_name="Prénom")),
                ("phone", models.CharField(max_length=20, verbose_name="Téléphone")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("guests", models.IntegerField(verbose_name="Nombre de personnes")),
                (
                    "reservation_date",
                    models.DateField(verbose_name="Date de réservation"),
                ),
                (
                    "reservation_time",
                    models.TimeField(verbose_name="Heure de réservation"),
                ),
                (
                    "motif",
                    models.TextField(
                        blank=True, null=True, verbose_name="Motif spécial"
                    ),
                ),
                (
                    "table",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Table"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_confirmed",
                    models.BooleanField(default=False, verbose_name="Confirmée"),
                ),
                (
                    "is_cancelled",
                    models.BooleanField(default=False, verbose_name="Annulée"),
                ),
            ],
            options={
                "verbose_name": "Réservation",
                "verbose_name_plural": "Réservations",
                "db_table": "reservations",
                "ordering": ["-created_at"],
            },
        ),
    ]
