# Generated by Django 5.0.2 on 2025-08-23 13:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("guests", models.IntegerField()),
                ("reservation_date", models.DateField()),
                ("reservation_time", models.TimeField()),
                ("motif", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_confirmed", models.BooleanField(default=False)),
                ("is_cancelled", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "reservations",
                "ordering": ["-created_at"],
            },
        ),
    ]
